import { useEffect, useState, type FormEvent } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { post, put } from '../api'
import { EmptyState, ErrorState, PageHeader, PageLoader, ProgressBar, RadarChart, StatCard, type Skills } from '../components'
import { formatDate, useApiData } from '../hooks'
import { DevelopmentProfile } from '../DevelopmentProfile'
import { CityInput } from '../CityInput'

type Profile = { id: number; firstName: string; lastName: string; dateOfBirth: string; gender?: string; city?: string; preferredPosition: string; dominantFoot: string; experienceLevel: string; height?: number; weight?: number }
type Exercise = { trainingExerciseId: number; exerciseId: number; name: string; description: string; instructions: string; skillCategory: string; difficulty: number; durationMinutes: number; targetDurationMinutes?: number; targetRepetitions?: number; equipment: string }
type Day = { id: number; plannedDate: string; title: string; session?: { id: number; status: string; completedAt?: string }; exercises: Exercise[] }
type Plan = { id: number; weekStart: string; status: string; generationReason: string; days: Day[] }
type Dashboard = { profile: Profile; level: number; weakestSkills: { key: string; name: string; score: number }[]; weeklyCompletion: number; nextWorkout?: { id: number; title: string; plannedDate: string; duration: number }; plan?: Plan; achievements: { name: string; description: string; awardedAt: string }[]; skills?: Skills }

export function PlayerDashboard() {
  const { data, loading, error, reload } = useApiData<Dashboard>('/api/player/dashboard')
  if (loading) return <PageLoader />; if (error || !data) return <ErrorState message={error} retry={reload} />
  return <><PageHeader eyebrow="Личный кабинет" title={`Привет, ${data.profile.firstName}!`} actions={<Link className="button" to="/player/training">Открыть план</Link>} />
    <section className="dashboard-hero"><div><span className="eyebrow">Эта неделя</span><h2>{data.nextWorkout ? data.nextWorkout.title : 'Пора составить план'}</h2><p>{data.nextWorkout ? `${formatDate(data.nextWorkout.plannedDate)} · ${data.nextWorkout.duration} минут` : 'Пройдите тестирование, чтобы получить персональную неделю.'}</p>{data.nextWorkout ? <Link className="button large" to="/player/training">К тренировке →</Link> : <Link className="button large" to="/player/assessment">Начать тестирование →</Link>}</div><div className="completion-ring" style={{ '--value': `${data.weeklyCompletion * 3.6}deg` } as React.CSSProperties}><strong>{data.weeklyCompletion}%</strong><span>плана</span></div></section>
    <section className="stat-grid"><StatCard label="Текущий уровень" value={Math.round(data.level)} detail="из 100" tone="accent" /><StatCard label="Фокус развития" value={data.weakestSkills[0]?.name ?? 'Нужен тест'} detail={data.weakestSkills[0] ? `${data.weakestSkills[0].score} / 100` : undefined} /><StatCard label="Тренировок в плане" value={data.plan?.days.length ?? 0} detail="на текущую неделю" /></section>
    <div className="content-grid"><section className="card"><div className="card-heading"><div><span className="eyebrow">Баланс игрока</span><h2>Шесть навыков</h2></div><Link to="/player/progress">История →</Link></div>{data.skills ? <RadarChart values={data.skills} /> : <EmptyState title="Ещё нет результатов"><Link to="/player/assessment">Пройти тесты</Link></EmptyState>}</section>
      <section className="card"><div className="card-heading"><div><span className="eyebrow">На этой неделе</span><h2>План</h2></div></div>{data.plan?.days.map((day, index) => <article className="day-row" key={day.id}><span className={day.session?.status === 'Completed' ? 'day-number complete' : 'day-number'}>{day.session?.status === 'Completed' ? '✓' : index + 1}</span><div><strong>{day.title}</strong><small>{formatDate(day.plannedDate)} · {day.exercises.length} упражнения</small></div><span>→</span></article>) ?? <EmptyState title="План появится после тестирования" />}</section>
    </div>
    {data.achievements.length > 0 && <section className="card achievements"><div className="card-heading"><h2>Последние достижения</h2></div>{data.achievements.map(x => <article key={x.name}><span>◆</span><div><strong>{x.name}</strong><small>{x.description}</small></div></article>)}</section>}
  </>
}

export function ProfilePage() {
  const { data, loading, error, reload } = useApiData<Profile>('/api/player/profile'); const [message, setMessage] = useState('')
  if (loading) return <PageLoader />; if (error || !data) return <ErrorState message={error} retry={reload} />
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); setMessage(''); try { await put('/api/player/profile', { firstName: f.get('firstName'), lastName: f.get('lastName'), gender: f.get('gender') || null, city: f.get('city'), preferredPosition: f.get('preferredPosition'), dominantFoot: f.get('dominantFoot'), experienceLevel: f.get('experienceLevel'), height: f.get('height') ? Number(f.get('height')) : null, weight: f.get('weight') ? Number(f.get('weight')) : null }); setMessage('Изменения сохранены.') } catch (e) { setMessage(e instanceof Error ? e.message : 'Ошибка сохранения.') } }
  return <><PageHeader eyebrow="Профиль игрока" title="Мои данные" /><section className="card form-card"><form className="profile-form" onSubmit={submit}><label>Имя<input name="firstName" defaultValue={data.firstName} required /></label><label>Фамилия<input name="lastName" defaultValue={data.lastName} required /></label><label>Дата рождения<input value={data.dateOfBirth} disabled /></label><label>Город<CityInput defaultValue={data.city ?? ''} required /></label><label>Пол (необязательно)<select name="gender" defaultValue={data.gender ?? ''}><option value="">Не указан</option><option>Мужской</option><option>Женский</option></select></label><label>Позиция<select name="preferredPosition" defaultValue={data.preferredPosition} required><option value="" disabled>Выберите позицию</option><option>Вратарь</option><option>Защитник</option><option>Полузащитник</option><option>Нападающий</option></select></label><label>Ведущая нога<select name="dominantFoot" defaultValue={data.dominantFoot} required><option value="" disabled>Выберите ведущую ногу</option><option>Правая</option><option>Левая</option><option>Обе</option></select></label><label>Уровень<select name="experienceLevel" defaultValue={data.experienceLevel} required><option value="" disabled>Выберите уровень</option><option>Начинающий</option><option>Любитель</option><option>Опытный</option></select></label><label>Рост, см<input name="height" type="number" min="80" max="230" step="0.1" defaultValue={data.height} /></label><label>Вес, кг<input name="weight" type="number" min="20" max="250" step="0.1" defaultValue={data.weight} /></label><div className="form-actions"><button className="button">Сохранить</button>{message && <span role="status">{message}</span>}</div></form></section></>
}

type AssessmentDefinition = { id: number; name: string; description: string; instructions: string; unit: string; skillCategory: string; minimumReasonableValue: number; maximumReasonableValue: number }
type AssessmentData = { definitions: AssessmentDefinition[]; session?: { id: number; values: { definitionId: number; value: number }[] }; demoNotice: string }
export function AssessmentPage() {
  const { data, loading, error, reload } = useApiData<AssessmentData>('/api/assessments/current'); const [result, setResult] = useState<{ skills: Skills; weakest: { name: string; score: number }[] } | null>(null)
  if (loading) return <PageLoader />; if (error || !data) return <ErrorState message={error} retry={reload} />
  if (result) return <><PageHeader eyebrow="Тестирование завершено" title="Твоя точка отсчёта" /><div className="content-grid"><section className="card"><RadarChart values={result.skills} /></section><section className="card result-panel"><span className="eyebrow">Фокус недели</span><h2>{result.weakest.map(x => x.name).join(' · ')}</h2><p>Мы уже собрали новый план с повышенным весом этих навыков.</p><Link className="button large" to="/player/training">Открыть план →</Link></section></div></>
  return <><PageHeader eyebrow="Диагностика" title="Шесть тестов — честный старт" /><AssessmentForm data={data} onComplete={setResult} /></>
}

export function AssessmentForm({ data, onComplete }: { data: AssessmentData; onComplete: (value: { skills: Skills; weakest: { name: string; score: number }[] }) => void }) {
  const initial = Object.fromEntries(data.session?.values.map(x => [x.definitionId, String(x.value)]) ?? []) as Record<number, string>
  const [step, setStep] = useState(0); const [values, setValues] = useState<Record<number, string>>(initial); const [error, setError] = useState(''); const [pending, setPending] = useState(false)
  const definition = data.definitions[step]; const value = Number(values[definition.id]); const valid = values[definition.id] !== undefined && values[definition.id] !== '' && value >= definition.minimumReasonableValue && value <= definition.maximumReasonableValue
  const next = async () => { if (!valid) return setError(`Введите значение от ${definition.minimumReasonableValue} до ${definition.maximumReasonableValue} ${definition.unit}.`); setError(''); await put('/api/assessments/draft', { values: [{ definitionId: definition.id, value }] }); if (step < data.definitions.length - 1) setStep(step + 1); else { setPending(true); try { const response = await post<{ skills: Skills; weakest: { name: string; score: number }[] }>('/api/assessments/submit', { values: data.definitions.map(x => ({ definitionId: x.id, value: Number(values[x.id]) })) }); onComplete(response) } catch (e) { setError(e instanceof Error ? e.message : 'Тестирование не отправлено.') } finally { setPending(false) } } }
  return <section className="assessment-card"><div className="assessment-progress"><div><span>Тест {step + 1} из {data.definitions.length}</span><strong>{Math.round((step + 1) / data.definitions.length * 100)}%</strong></div><ProgressBar value={(step + 1) / data.definitions.length * 100} /></div><div className="assessment-body"><aside>{data.definitions.map((x, i) => <button key={x.id} className={i === step ? 'active' : values[x.id] ? 'done' : ''} onClick={() => setStep(i)}><span>{values[x.id] ? '✓' : i + 1}</span>{x.name}</button>)}</aside><div className="assessment-question"><span className="skill-chip">{skillRu(definition.skillCategory)}</span><h2>{definition.name}</h2><p>{definition.description}</p><div className="instruction"><strong>Как выполнить</strong><p>{definition.instructions}</p></div><label className="result-input">Результат<div><input aria-label={`Результат: ${definition.name}`} type="number" min={definition.minimumReasonableValue} max={definition.maximumReasonableValue} step="0.01" value={values[definition.id] ?? ''} onChange={e => setValues({ ...values, [definition.id]: e.target.value })} /><span>{definition.unit}</span></div></label>{error && <div className="form-error" role="alert">{error}</div>}<div className="question-actions"><button className="button ghost" disabled={step === 0} onClick={() => setStep(step - 1)}>Назад</button><button className="button" disabled={pending} onClick={() => void next()}>{step === data.definitions.length - 1 ? (pending ? 'Считаем…' : 'Завершить') : 'Сохранить и дальше →'}</button></div><small className="demo-warning">{data.demoNotice}</small></div></div></section>
}

export function TrainingPlanPage() {
  const { data, loading, error, reload } = useApiData<Plan>('/api/training/plan'); const navigate = useNavigate(); const [starting, setStarting] = useState<number | null>(null)
  if (loading) return <PageLoader />; if (error) return <ErrorState message={error} retry={reload} />; if (!data) return <><PageHeader title="План тренировок" /><EmptyState title="План ещё не создан"><Link to="/player/assessment">Пройти тестирование</Link></EmptyState></>
  const start = async (day: Day) => { if (day.session?.id) return navigate(`/player/training/${day.session.id}`); setStarting(day.id); try { const result = await post<{ id: number }>(`/api/training/days/${day.id}/start`); navigate(`/player/training/${result.id}`) } finally { setStarting(null) } }
  return <><PageHeader eyebrow={`Неделя от ${formatDate(data.weekStart)}`} title="Твой тренировочный план" /><div className="plan-reason"><span>◎</span><div><strong>Почему такой план</strong><p>{data.generationReason}</p></div></div><section className="week-grid">{data.days.map((day, index) => <article className={`training-day ${day.session?.status === 'Completed' ? 'completed' : ''}`} key={day.id}><header><span>День {index + 1}</span><time>{formatDate(day.plannedDate)}</time></header><h2>{day.title}</h2><ul>{day.exercises.map(x => <li key={x.trainingExerciseId}><span className="exercise-skill">{skillIcon(x.skillCategory)}</span><div><strong>{x.name}</strong><small>{x.durationMinutes} мин · {skillRu(x.skillCategory)}</small></div></li>)}</ul><button className={day.session?.status === 'Completed' ? 'button ghost' : 'button'} onClick={() => void start(day)} disabled={starting === day.id}>{day.session?.status === 'Completed' ? 'Посмотреть результат' : day.session ? 'Продолжить' : starting === day.id ? 'Запускаем…' : 'Начать тренировку'}</button></article>)}</section></>
}

type ExerciseResult = { isCompleted: boolean; durationMinutes?: number | null; repetitions?: number | null; notes?: string | null; perceivedDifficulty?: number | null }
type Workout = { id: number; status: string; startedAt: string; completedAt?: string; notes?: string; day: { title: string; plannedDate: string }; exercises: (Exercise & { result?: ExerciseResult })[] }
export function WorkoutPage() {
  const { sessionId } = useParams(); const { data, setData, loading, error, reload } = useApiData<Workout>(sessionId ? `/api/training/sessions/${sessionId}` : null); const navigate = useNavigate(); const [message, setMessage] = useState(''); const [sessionNotes, setSessionNotes] = useState(''); const [completing, setCompleting] = useState(false)
  useEffect(() => { setSessionNotes(data?.notes ?? '') }, [data?.id, data?.notes])
  if (loading) return <PageLoader />; if (error || !data) return <ErrorState message={error} retry={reload} />
  const update = async (exercise: Workout['exercises'][number], patch: { isCompleted?: boolean; notes?: string | null; perceivedDifficulty?: number | null }) => {
    const current = exercise.result
    const result: ExerciseResult = { isCompleted: patch.isCompleted ?? current?.isCompleted ?? false, durationMinutes: current?.durationMinutes ?? exercise.targetDurationMinutes ?? null, repetitions: current?.repetitions ?? exercise.targetRepetitions ?? null, notes: patch.notes === undefined ? current?.notes ?? null : patch.notes, perceivedDifficulty: patch.perceivedDifficulty === undefined ? current?.perceivedDifficulty ?? null : patch.perceivedDifficulty }
    await put(`/api/training/sessions/${data.id}/exercises/${exercise.trainingExerciseId}`, result)
    setData({ ...data, exercises: data.exercises.map(x => x.trainingExerciseId === exercise.trainingExerciseId ? { ...x, result } : x) })
  }
  const complete = async () => { if (data.exercises.some(x => !x.result?.isCompleted)) return setMessage('Отметьте все упражнения перед завершением.'); setMessage(''); setCompleting(true); try { await post(`/api/training/sessions/${data.id}/complete`, { notes: sessionNotes.trim() || null }); navigate('/player/progress') } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось завершить тренировку. Попробуйте ещё раз.') } finally { setCompleting(false) } }
  const done = data.exercises.filter(x => x.result?.isCompleted).length
  return <><PageHeader eyebrow={formatDate(data.day.plannedDate)} title={data.day.title} actions={<span className="session-timer">● Тренировка сохраняется</span>} /><ProgressBar value={done / data.exercises.length * 100} label={`${done} из ${data.exercises.length} выполнено`} /><section className="workout-list">{data.exercises.map((x, index) => <article className={x.result?.isCompleted ? 'workout-exercise done' : 'workout-exercise'} key={x.trainingExerciseId}><button aria-label={`${x.result?.isCompleted ? 'Снять отметку' : 'Отметить'}: ${x.name}`} className="check-button" onClick={() => void update(x, { isCompleted: !x.result?.isCompleted })}>{x.result?.isCompleted ? '✓' : index + 1}</button><div className="exercise-content"><span className="skill-chip">{skillRu(x.skillCategory)}</span><h2>{x.name}</h2><p>{x.instructions}</p><div className="exercise-meta"><span>◷ {x.targetDurationMinutes} мин</span><span>◇ {x.equipment}</span></div><div className="exercise-feedback"><label>Сложность для тебя<select aria-label={`Сложность: ${x.name}`} value={x.result?.perceivedDifficulty ?? ''} onChange={e => void update(x, { perceivedDifficulty: e.target.value ? Number(e.target.value) : null })}><option value="">Не указана</option><option value="1">1 — очень легко</option><option value="2">2 — легко</option><option value="3">3 — нормально</option><option value="4">4 — сложно</option><option value="5">5 — очень сложно</option></select></label><label>Комментарий<input aria-label={`Комментарий: ${x.name}`} defaultValue={x.result?.notes ?? ''} placeholder="Необязательно" onBlur={e => void update(x, { notes: e.target.value.trim() || null })} /></label></div></div></article>)}</section><label className="workout-note">Комментарий по тренировке<textarea value={sessionNotes} onChange={e => setSessionNotes(e.target.value)} placeholder="Что получилось, что хотелось бы улучшить" /></label>{message && <div className="form-error" role="alert">{message}</div>}<div className="sticky-complete"><button className="button large" disabled={completing} onClick={() => void complete()}>{completing ? 'Завершаем…' : 'Завершить тренировку'}</button></div></>
}

type Progress = { completedSessions: number; adherence: number; assessmentHistory: { capturedAt: string; skills: Skills }[]; recentActivity: { id: number; status: string; startedAt?: string; completedAt?: string; title: string }[] }
export function ProgressPage() {
  const { data, loading, error, reload } = useApiData<Progress>('/api/player/progress')
  const history = data?.assessmentHistory ?? []; const latest = history.at(-1); const previous = history.at(-2)
  if (loading) return <PageLoader />; if (error || !data) return <ErrorState message={error} retry={reload} />
  return <><PageHeader eyebrow="Динамика" title="Прогресс в цифрах" /><DevelopmentProfile endpoint="/api/player/development" title="Моя работа с командой" /><section className="stat-grid"><StatCard label="Самостоятельных тренировок" value={data.completedSessions} tone="accent" /><StatCard label="Соблюдение личного плана" value={`${data.adherence}%`} /><StatCard label="Тестирований" value={history.length} /></section><div className="content-grid"><section className="card"><div className="card-heading"><div><span className="eyebrow">Сравнение</span><h2>Диагностика навыков</h2></div></div>{latest ? <RadarChart values={latest.skills} previous={previous?.skills} /> : <EmptyState title="История пока пуста" />}</section><section className="card"><div className="card-heading"><h2>Личный план</h2></div>{data.recentActivity.length ? data.recentActivity.map(x => <article className="activity-row" key={x.id}><span>{x.status === 'Completed' ? '✓' : '▶'}</span><div><strong>{x.title}</strong><small>{formatDate(x.completedAt ?? x.startedAt)}</small></div></article>) : <EmptyState title="Самостоятельных тренировок пока нет" />}</section></div></>
}

function skillRu(value: string) { return ({ Speed: 'Скорость', Endurance: 'Выносливость', BallControl: 'Контроль мяча', Passing: 'Передачи', Shooting: 'Удары', Agility: 'Ловкость' } as Record<string, string>)[value] ?? value }
function skillIcon(value: string) { return ({ Speed: '↗', Endurance: '∞', BallControl: '●', Passing: '→', Shooting: '◎', Agility: '◇' } as Record<string, string>)[value] ?? '◆' }
