import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { post, put, remove } from '../api'
import { EmptyState, ErrorState, PageHeader, PageLoader, ProgressBar, StatCard } from '../components'
import { formatDate, useApiData } from '../hooks'

type Membership = { schoolId: number; name: string; role: string }
type Coach = { userId: string; email: string; isActive: boolean; coachId?: number; displayName?: string }
type TeamSummary = { id: number; name: string; ageGroup?: string; season?: string; trainingCycleStage: string; displayName: string; players: number; coaches: number; headCoach?: string; trainingsThisWeek: number; unfinished: number }
type Overview = { id: number; name: string; teams: number; coaches: number; players: number; trainingsThisWeek: number; unfinishedTrainings: number; attendanceRate: number; attentionPlayers: number; teamsWithoutCoach: number; teamsWithoutPlayers: number; teamSummaries: TeamSummary[] }
type Team = { id: number; name: string; ageGroup?: string; season?: string; trainingCycleStage: string; cycleStart?: string; cycleEnd?: string; displayName: string; isActive: boolean; players: number; groups: number; upcomingTraining?: string; coaches: { coachId: number; displayName: string; isHeadCoach: boolean }[] }
type Workspace = {
  team: { id: number; name: string; ageGroup?: string; season?: string; trainingCycleStage: string; cycleStart?: string; cycleEnd?: string; tacticFormation?: string; tacticNotes?: string; displayName: string; isActive: boolean; coaches: { coachId: number; displayName: string; isHeadCoach: boolean }[] }
  players: { playerId: number; firstName: string; lastName: string; dateOfBirth: string; preferredPosition: string; shirtNumber?: number }[]
  groups: { id: number; name: string; purpose?: string; players: { playerId: number; firstName: string; lastName: string }[] }[]
  trainings: { id: number; title: string; scheduledAt: string; status: string; players: number; present: number }[]
  matches: { id: number; opponent: string; competition?: string; scheduledAt: string; venue: string; status: string; goalsFor?: number; goalsAgainst?: number; lineupNotes?: string }[]
  tournaments: { id: number; name: string; startDate: string; endDate?: string; status: string; placement?: string; entryFee: number; travelCost: number; accommodationCost: number; mealCost: number; equipmentCost: number; otherCost: number; income: number }[]
  metrics: { attendanceRate: number; completionRate: number; understandingRate: number; trainingsCompleted: number; attentionPlayers: number; tournamentExpenses: number; tournamentIncome: number }
}
type Notice = { text: string; ok: boolean } | null
type TeamTab = 'overview' | 'roster' | 'collective' | 'tactics' | 'training' | 'matches' | 'tournaments' | 'economy'

const cycleStages = ['Подготовительный этап', 'Базовый этап', 'Соревновательный этап', 'Восстановительный этап', 'Переходный этап']
const teamTabs: { id: TeamTab; label: string }[] = [
  { id: 'overview', label: 'Обзор' }, { id: 'roster', label: 'Состав' }, { id: 'collective', label: 'Коллектив' }, { id: 'tactics', label: 'Тактика' },
  { id: 'training', label: 'Тренировки' }, { id: 'matches', label: 'Матчи' }, { id: 'tournaments', label: 'Турниры' }, { id: 'economy', label: 'Экономика' },
]

function SchoolBoundary({ children }: { children: (schoolId: number) => ReactNode }) {
  const state = useApiData<Membership[]>('/api/school/memberships')
  if (state.loading) return <PageLoader />
  if (state.error) return <ErrorState message={state.error} retry={state.reload} />
  const schoolId = state.data?.[0]?.schoolId
  if (!schoolId) return <EmptyState title="Нет доступной школы">Обратитесь к администратору платформы.</EmptyState>
  return children(schoolId)
}

export function SchoolDashboardPage() { return <SchoolBoundary>{schoolId => <SchoolOverview schoolId={schoolId} />}</SchoolBoundary> }
function SchoolOverview({ schoolId }: { schoolId: number }) {
  const state = useApiData<Overview>(`/api/school/${schoolId}/overview`)
  if (state.loading) return <PageLoader />
  if (state.error || !state.data) return <ErrorState message={state.error} retry={state.reload} />
  const school = state.data
  const issues = school.teamsWithoutCoach + school.teamsWithoutPlayers + school.unfinishedTrainings + school.attentionPlayers
  return <>
    <PageHeader eyebrow="Управление школой" title={school.name} actions={<Link className="button" to="/school/teams">Открыть команды →</Link>} />
    <p className="school-hint">Назначьте тренеров и распределите игроков по составам — каждый тренер будет видеть только свои команды и игроков.</p>
    <section className="stat-grid school-core-stats"><StatCard label="Составов" value={school.teams} /><StatCard label="Тренеров" value={school.coaches} /><StatCard label="Игроков" value={school.players} /></section>
    <section className="school-dashboard-grid">
      <article className="card school-pulse">
        <div className="card-heading"><div><span className="eyebrow">Последние 30 дней</span><h2>Работа школы</h2></div><span className={`health-indicator ${issues ? 'attention' : ''}`}>{issues ? `${issues} требуют действий` : 'Всё в порядке'}</span></div>
        <div className="pulse-grid"><div><strong>{school.trainingsThisWeek}</strong><span>тренировок завершено за неделю</span></div><div><strong>{school.attendanceRate}%</strong><span>средняя посещаемость</span></div><div><strong>{school.unfinishedTrainings}</strong><span>журналов не завершено</span></div><div><strong>{school.attentionPlayers}</strong><span>игроков требуют внимания</span></div></div>
      </article>
      <article className="card action-center">
        <div className="card-heading"><div><span className="eyebrow">Контроль</span><h2>Что проверить</h2></div></div>
        <ActionRow value={school.teamsWithoutCoach} label="Составы без тренера" href="/school/teams" /><ActionRow value={school.teamsWithoutPlayers} label="Составы без игроков" href="/school/teams" /><ActionRow value={school.unfinishedTrainings} label="Незавершённые журналы" href="/school/teams" /><ActionRow value={school.attentionPlayers} label="Игроки, которым нужна работа" href="/school/players" />
      </article>
    </section>
    <section className="card school-team-summary">
      <div className="card-heading"><div><span className="eyebrow">Все составы</span><h2>Команды школы</h2></div><Link to="/school/teams">Управление →</Link></div>
      {school.teamSummaries.length ? <div className="team-summary-list">{school.teamSummaries.map(team => <Link to={`/school/teams?team=${team.id}`} key={team.id}><div><strong>{team.displayName}</strong><small>{team.headCoach || 'Тренер не назначен'} · {team.trainingCycleStage}</small></div><span>{team.players}<small>игроков</small></span><span>{team.trainingsThisWeek}<small>тренировок</small></span><span className={team.unfinished ? 'warn' : ''}>{team.unfinished}<small>не завершено</small></span><b>→</b></Link>)}</div> : <EmptyState title="Составов пока нет">Создайте первую команду и назначьте тренера.</EmptyState>}
    </section>
  </>
}

function ActionRow({ value, label, href }: { value: number; label: string; href: string }) { return <Link className={value ? 'action-row attention' : 'action-row'} to={href}><span>{value ? '!' : '✓'}</span><strong>{label}</strong><b>{value}</b></Link> }

export function SchoolTeamsPage() { return <SchoolBoundary>{schoolId => <Teams schoolId={schoolId} />}</SchoolBoundary> }
function Teams({ schoolId }: { schoolId: number }) {
  const state = useApiData<Team[]>(`/api/school/${schoolId}/teams`)
  const coaches = useApiData<Coach[]>(`/api/school/${schoolId}/coaches`)
  const [params, setParams] = useSearchParams()
  const [showCreate, setShowCreate] = useState(false)
  const [tab, setTab] = useState<TeamTab>('overview')
  const [notice, setNotice] = useState<Notice>(null)
  const activeTeams = useMemo(() => state.data?.filter(x => x.isActive) ?? [], [state.data])
  const selectedId = Number(params.get('team')) || activeTeams[0]?.id || 0
  const workspace = useApiData<Workspace>(selectedId ? `/api/school/${schoolId}/teams/${selectedId}/workspace` : null)
  useEffect(() => { if (!params.get('team') && activeTeams[0]) setParams({ team: String(activeTeams[0].id) }, { replace: true }) }, [activeTeams, params, setParams])
  const reloadAll = async () => { await Promise.all([state.reload(), workspace.reload()]) }
  const create = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; const f = new FormData(form); setNotice(null)
    try { const result = await post<{ id: number }>(`/api/school/${schoolId}/teams`, { name: f.get('name'), ageGroup: f.get('ageGroup'), season: f.get('season'), trainingCycleStage: f.get('trainingCycleStage'), cycleStart: f.get('cycleStart') || null, cycleEnd: f.get('cycleEnd') || null, headCoachId: f.get('headCoachId') ? Number(f.get('headCoachId')) : null, isActive: true }); form.reset(); setShowCreate(false); setParams({ team: String(result.id) }); setNotice({ text: 'Состав создан.', ok: true }); await state.reload() }
    catch (e) { setNotice({ text: e instanceof Error ? e.message : 'Не удалось создать состав.', ok: false }) }
  }
  if (state.loading) return <PageLoader />
  if (state.error || !state.data) return <ErrorState message={state.error} retry={state.reload} />
  return <>
    <PageHeader eyebrow="Школа" title="Команды" actions={<button className="button" onClick={() => setShowCreate(true)}>+ Создать команду</button>} />
    {notice && <p className={notice.ok ? 'success-message' : 'error-message'}>{notice.text}</p>}
    {showCreate && <Modal title="Новая команда и состав" onClose={() => setShowCreate(false)}><TeamCreateForm coaches={coaches.data ?? []} submit={create} /></Modal>}
    {activeTeams.length ? <><section className="team-context-bar"><label><small>КОМАНДА И СОСТАВ</small><select value={selectedId} onChange={e => { setParams({ team: e.target.value }); setTab('overview') }}>{activeTeams.map(team => <option key={team.id} value={team.id}>{team.displayName}</option>)}</select></label>{workspace.data && <div className="team-context-meta"><span><small>Главный тренер</small><strong>{workspace.data.team.coaches.find(x => x.isHeadCoach)?.displayName || 'Не назначен'}</strong></span><span><small>Игроков</small><strong>{workspace.data.players.length}</strong></span><span><small>Цикл</small><strong>{workspace.data.team.trainingCycleStage}</strong></span><span><small>Сезон</small><strong>{workspace.data.team.season || '—'}</strong></span></div>}</section><nav className="team-subnav" aria-label="Разделы команды">{teamTabs.map(item => <button className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)} key={item.id}>{item.label}</button>)}</nav>{workspace.loading ? <PageLoader /> : workspace.error || !workspace.data ? <ErrorState message={workspace.error} retry={workspace.reload} /> : <TeamWorkspace schoolId={schoolId} data={workspace.data} coaches={coaches.data ?? []} tab={tab} reload={reloadAll} setNotice={setNotice} />}</> : <section className="card"><EmptyState title="Команд пока нет">Создайте возрастную команду и первый состав — после этого можно назначить тренера и добавить игроков.</EmptyState></section>}
  </>
}

function TeamCreateForm({ coaches, submit }: { coaches: Coach[]; submit: (event: FormEvent<HTMLFormElement>) => void }) { return <form className="profile-form team-create-form" onSubmit={submit}><label>Возрастная команда<input name="ageGroup" placeholder="U17" required /></label><label>Состав<select name="name" defaultValue="Первый состав"><option>Первый состав</option><option>Второй состав</option><option>Резервный состав</option></select></label><label>Сезон<input name="season" defaultValue="2026/27" /></label><label>Главный тренер<select name="headCoachId"><option value="">Назначить позже</option>{coaches.filter(x => x.coachId && x.isActive).map(x => <option value={x.coachId} key={x.userId}>{x.displayName}</option>)}</select></label><label>Стадия цикла<select name="trainingCycleStage">{cycleStages.map(x => <option key={x}>{x}</option>)}</select></label><label>Начало цикла<input name="cycleStart" type="date" /></label><label>Окончание цикла<input name="cycleEnd" type="date" /></label><div className="form-actions"><button className="button">Создать состав</button></div></form> }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onMouseDown={e => { if (e.currentTarget === e.target) onClose() }}><section className="modal-panel" role="dialog" aria-modal="true" aria-label={title}><div className="card-heading"><h2>{title}</h2><button className="modal-close" onClick={onClose} aria-label="Закрыть">×</button></div>{children}</section></div> }

function TeamWorkspace({ schoolId, data, coaches, tab, reload, setNotice }: { schoolId: number; data: Workspace; coaches: Coach[]; tab: TeamTab; reload: () => Promise<void>; setNotice: (value: Notice) => void }) {
  const [panel, setPanel] = useState<'group' | 'match' | 'tournament' | null>(null)
  const save = async (path: string, value: unknown, ok: string) => { setNotice(null); try { await post(path, value); setPanel(null); setNotice({ text: ok, ok: true }); await reload() } catch (e) { setNotice({ text: e instanceof Error ? e.message : 'Не удалось сохранить данные.', ok: false }) } }
  const assign = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); await save(`/api/school/${schoolId}/teams/${data.team.id}/coaches`, { coachId: Number(f.get('coachId')), isHeadCoach: f.get('isHeadCoach') === 'on' }, 'Тренер назначен.') }
  const unassign = async (coachId: number) => { try { await remove(`/api/school/${schoolId}/teams/${data.team.id}/coaches/${coachId}`); setNotice({ text: 'Тренер снят с состава.', ok: true }); await reload() } catch (e) { setNotice({ text: e instanceof Error ? e.message : 'Не удалось снять тренера.', ok: false }) } }
  return <section className="team-workspace">
    {tab === 'overview' && <TeamOverview schoolId={schoolId} data={data} reload={reload} setNotice={setNotice} />}
    {tab === 'roster' && <><div className="section-toolbar"><div><span className="eyebrow">Состав команды</span><h2>{data.players.length} игроков</h2></div><button className="button ghost" onClick={() => setPanel(panel === 'group' ? null : 'group')}>+ Тренировочная группа</button></div>{panel === 'group' && <GroupForm players={data.players} submit={value => save(`/api/school/${schoolId}/teams/${data.team.id}/groups`, value, 'Тренировочная группа создана.')} />}<Roster data={data} /><section className="card staff-panel"><div className="card-heading"><h2>Тренерский штаб</h2></div><div className="assigned-staff">{data.team.coaches.map(x => <span key={x.coachId}><b>{x.isHeadCoach ? 'Главный тренер' : 'Тренер'}</b>{x.displayName}<button onClick={() => void unassign(x.coachId)}>×</button></span>)}</div><form className="inline-assign" onSubmit={assign}><select name="coachId" required><option value="">Выберите тренера</option>{coaches.filter(x => x.coachId && x.isActive && !data.team.coaches.some(c => c.coachId === x.coachId)).map(x => <option value={x.coachId} key={x.userId}>{x.displayName}</option>)}</select><label className="checkbox"><input name="isHeadCoach" type="checkbox" />Главный</label><button className="button ghost">Назначить</button></form></section></>}
    {tab === 'collective' && <Collective data={data} />}{tab === 'tactics' && <Tactics data={data} />}{tab === 'training' && <TrainingList data={data} />}
    {tab === 'matches' && <><SectionToolbar eyebrow="Календарь" title="Матчи" action="+ Добавить матч" click={() => setPanel(panel === 'match' ? null : 'match')} />{panel === 'match' && <MatchForm submit={value => save(`/api/school/${schoolId}/teams/${data.team.id}/matches`, value, 'Матч добавлен.')} />}<Matches data={data} /></>}
    {tab === 'tournaments' && <><SectionToolbar eyebrow="Соревнования" title="Турниры" action="+ Добавить турнир" click={() => setPanel(panel === 'tournament' ? null : 'tournament')} />{panel === 'tournament' && <TournamentForm submit={value => save(`/api/school/${schoolId}/teams/${data.team.id}/tournaments`, value, 'Турнир добавлен.')} />}<Tournaments data={data} /></>}
    {tab === 'economy' && <Economy data={data} />}
  </section>
}

function SectionToolbar({ eyebrow, title, action, click }: { eyebrow: string; title: string; action: string; click: () => void }) { return <div className="section-toolbar"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><button className="button ghost" onClick={click}>{action}</button></div> }

function TeamOverview({ schoolId, data, reload, setNotice }: { schoolId: number; data: Workspace; reload: () => Promise<void>; setNotice: (value: Notice) => void }) {
  const nextTraining = [...data.trainings].filter(x => new Date(x.scheduledAt) >= new Date()).sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt))[0]
  const nextMatch = [...data.matches].filter(x => new Date(x.scheduledAt) >= new Date()).sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt))[0]
  const update = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); try { await put(`/api/school/${schoolId}/teams/${data.team.id}`, { name: data.team.name, ageGroup: data.team.ageGroup, season: f.get('season'), trainingCycleStage: f.get('trainingCycleStage'), cycleStart: f.get('cycleStart') || null, cycleEnd: f.get('cycleEnd') || null, isActive: true }); setNotice({ text: 'Тренировочный цикл обновлён.', ok: true }); await reload() } catch (e) { setNotice({ text: e instanceof Error ? e.message : 'Не удалось обновить цикл.', ok: false }) } }
  return <><section className="stat-grid four team-kpis"><StatCard label="Посещаемость" value={`${data.metrics.attendanceRate}%`} tone="accent" /><StatCard label="Выполнение" value={`${data.metrics.completionRate}%`} /><StatCard label="Понимание" value={`${data.metrics.understandingRate}%`} /><StatCard label="Нужна работа" value={data.metrics.attentionPlayers} tone={data.metrics.attentionPlayers ? 'coral' : 'default'} /></section><section className="team-overview-grid"><article className="card cycle-card"><div className="card-heading"><div><span className="eyebrow">Тренировочный цикл</span><h2>{data.team.trainingCycleStage}</h2></div></div><form className="profile-form" onSubmit={update}><label>Этап<select name="trainingCycleStage" defaultValue={data.team.trainingCycleStage}>{cycleStages.map(x => <option key={x}>{x}</option>)}</select></label><label>Сезон<input name="season" defaultValue={data.team.season} /></label><label>Начало<input name="cycleStart" type="date" defaultValue={data.team.cycleStart} /></label><label>Окончание<input name="cycleEnd" type="date" defaultValue={data.team.cycleEnd} /></label><div className="form-actions"><button className="button ghost">Сохранить цикл</button></div></form></article><article className="card next-events"><div className="card-heading"><div><span className="eyebrow">Ближайшее</span><h2>План команды</h2></div></div><EventRow icon="✓" title={nextTraining?.title || 'Тренировка не запланирована'} date={nextTraining?.scheduledAt} detail={nextTraining ? 'Командная тренировка' : 'Добавляется тренером в журнале'} /><EventRow icon="⚑" title={nextMatch ? `Матч с ${nextMatch.opponent}` : 'Матч не запланирован'} date={nextMatch?.scheduledAt} detail={nextMatch?.competition || 'Добавьте матч в календарь'} /></article></section><section className="card overview-groups"><div className="card-heading"><div><span className="eyebrow">Работа внутри состава</span><h2>Тренировочные группы</h2></div></div>{data.groups.length ? <div className="group-cards">{data.groups.map(x => <article key={x.id}><strong>{x.name}</strong><small>{x.purpose || 'Без отдельной задачи'}</small><span>{x.players.length} игроков</span></article>)}</div> : <EmptyState title="Групп пока нет">Создавайте группы только под конкретную тренировочную задачу.</EmptyState>}</section></>
}

function EventRow({ icon, title, date, detail }: { icon: string; title: string; date?: string; detail: string }) { return <div className="event-row"><span>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><time>{date ? formatDate(date) : '—'}</time></div> }
function Roster({ data }: { data: Workspace }) { return <section className="card data-table roster-table"><div className="table-head"><span>Игрок</span><span>Позиция</span><span>Номер</span><span>Тренировочные группы</span></div>{data.players.map(player => <div key={player.playerId}><span><strong>{player.firstName} {player.lastName}</strong><small>{player.dateOfBirth}</small></span><span>{player.preferredPosition}</span><span>{player.shirtNumber ? `№ ${player.shirtNumber}` : '—'}</span><span className="table-chips">{data.groups.filter(g => g.players.some(x => x.playerId === player.playerId)).map(g => <small key={g.id}>{g.name}</small>)}{!data.groups.some(g => g.players.some(x => x.playerId === player.playerId)) && 'Общий состав'}</span></div>)}</section> }

function GroupForm({ players, submit }: { players: Workspace['players']; submit: (value: unknown) => void }) {
  const [selected, setSelected] = useState<number[]>([])
  return <section className="card inline-editor"><h2>Новая тренировочная группа</h2><form className="profile-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ name: f.get('name'), purpose: f.get('purpose'), playerIds: selected }) }}><label>Название<input name="name" placeholder="Вратари" required /></label><label>Задача<input name="purpose" placeholder="Работа на выходах" /></label><fieldset className="player-picker full"><legend>Игроки</legend>{players.map(x => <label className={selected.includes(x.playerId) ? 'selected' : ''} key={x.playerId}><input type="checkbox" checked={selected.includes(x.playerId)} onChange={() => setSelected(current => current.includes(x.playerId) ? current.filter(id => id !== x.playerId) : [...current, x.playerId])} />{x.firstName} {x.lastName}</label>)}</fieldset><div className="form-actions"><button className="button">Создать группу</button></div></form></section>
}

function Collective({ data }: { data: Workspace }) { const stability = data.players.length ? Math.max(0, 100 - data.metrics.attentionPlayers * 8) : 0; return <><section className="collective-hero card"><div><span className="eyebrow">Командная динамика</span><h2>{data.metrics.attentionPlayers ? 'Есть точки для тренерской работы' : 'Состав работает стабильно'}</h2><p>Показатели рассчитаны по журналам тренировок. Они помогают видеть тенденции, но не присваивают детям ярлыки.</p></div><div className="collective-score"><strong>{Math.round((data.metrics.attendanceRate + data.metrics.understandingRate + stability) / 3)}</strong><span>индекс стабильности</span></div></section><section className="card collective-bars"><ProgressBar value={data.metrics.attendanceRate} label="Регулярность посещения" /><ProgressBar value={data.metrics.understandingRate} label="Понимание заданий" /><ProgressBar value={stability} label="Стабильность состава" /></section></> }

function Tactics({ data }: { data: Workspace }) { return <section className="tactics-grid"><article className="card tactics-board">{['11', '7', '9', '10', '8', '6', '3', '4', '5', '2', '1'].map(x => <span key={x}>{x}</span>)}</article><article className="card tactic-readonly"><div className="card-heading"><div><span className="eyebrow">Предварительный план</span><h2>Тактика состава</h2></div><span className="count-chip">{data.team.tacticFormation || 'Схема не выбрана'}</span></div><div className="tactic-note"><small>Установка тренера</small><p>{data.team.tacticNotes || 'Тренер ещё не добавил предварительный состав и установку на игру.'}</p></div><div className="readonly-note">Обновляется тренером в разделе «Мои команды».</div></article></section> }

function TrainingList({ data }: { data: Workspace }) { return <section className="card timeline-list"><div className="card-heading"><div><span className="eyebrow">Общие и индивидуальные</span><h2>Последние тренировки</h2></div></div>{data.trainings.length ? data.trainings.map(x => <article key={x.id}><time>{formatDate(x.scheduledAt)}</time><div><strong>{x.title}</strong><small>{x.status === 'Completed' ? 'Завершена' : x.status === 'InProgress' ? 'Идёт' : 'Запланирована'} · {x.present}/{x.players} присутствовали</small></div><span className={x.status === 'Completed' ? 'done' : ''}>{x.status === 'Completed' ? '✓' : '→'}</span></article>) : <EmptyState title="Тренировок пока нет">Тренер создаст первую запись в журнале.</EmptyState>}</section> }
function Matches({ data }: { data: Workspace }) { return <section className="card timeline-list match-list">{data.matches.length ? data.matches.map(x => <article key={x.id}><time>{formatDate(x.scheduledAt)}</time><div><strong>{x.venue === 'Дома' ? data.team.displayName : x.opponent} — {x.venue === 'Дома' ? x.opponent : data.team.displayName}</strong><small>{x.competition || 'Без турнира'} · {x.venue}</small></div><b>{x.goalsFor == null ? x.status : `${x.goalsFor}:${x.goalsAgainst}`}</b></article>) : <EmptyState title="Матчей пока нет" />}</section> }
function MatchForm({ submit }: { submit: (value: unknown) => void }) { return <section className="card inline-editor"><form className="profile-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ opponent: f.get('opponent'), competition: f.get('competition'), scheduledAt: new Date(String(f.get('scheduledAt'))).toISOString(), venue: f.get('venue'), status: 'Запланирован' }) }}><label>Соперник<input name="opponent" required /></label><label>Соревнование<input name="competition" /></label><label>Дата и время<input name="scheduledAt" type="datetime-local" required /></label><label>Поле<select name="venue"><option>Дома</option><option>В гостях</option><option>Нейтральное</option></select></label><div className="form-actions"><button className="button">Добавить матч</button></div></form></section> }

function Tournaments({ data }: { data: Workspace }) { return <section className="tournament-grid">{data.tournaments.length ? data.tournaments.map(x => <article className="card tournament-card" key={x.id}><div className="card-heading"><div><span className="eyebrow">{x.status}</span><h2>{x.name}</h2></div>{x.placement && <span className="count-chip">{x.placement}</span>}</div><p>{x.startDate}{x.endDate ? ` — ${x.endDate}` : ''}</p><div><span><small>Расходы</small><b>{money(tournamentExpense(x))}</b></span><span><small>Доходы</small><b>{money(x.income)}</b></span></div></article>) : <section className="card"><EmptyState title="Турниров пока нет" /></section>}</section> }
function TournamentForm({ submit }: { submit: (value: unknown) => void }) { return <section className="card inline-editor"><form className="profile-form" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); const number = (name: string) => Number(f.get(name)) || 0; submit({ name: f.get('name'), startDate: f.get('startDate'), endDate: f.get('endDate') || null, status: 'Подготовка', placement: null, entryFee: number('entryFee'), travelCost: number('travelCost'), accommodationCost: number('accommodationCost'), mealCost: number('mealCost'), equipmentCost: 0, otherCost: 0, income: number('income') }) }}><label>Название<input name="name" required /></label><label>Начало<input name="startDate" type="date" required /></label><label>Окончание<input name="endDate" type="date" /></label><label>Взнос, ₽<input name="entryFee" type="number" min="0" /></label><label>Дорога, ₽<input name="travelCost" type="number" min="0" /></label><label>Проживание, ₽<input name="accommodationCost" type="number" min="0" /></label><label>Питание, ₽<input name="mealCost" type="number" min="0" /></label><label>Доходы, ₽<input name="income" type="number" min="0" /></label><div className="form-actions"><button className="button">Добавить турнир</button></div></form></section> }
function Economy({ data }: { data: Workspace }) { const balance = data.metrics.tournamentIncome - data.metrics.tournamentExpenses; return <><section className="stat-grid"><StatCard label="Расходы по турнирам" value={money(data.metrics.tournamentExpenses)} /><StatCard label="Доходы" value={money(data.metrics.tournamentIncome)} /><StatCard label="Баланс" value={money(balance)} tone={balance < 0 ? 'coral' : 'accent'} /></section><section className="card data-table economy-table"><div className="table-head"><span>Турнир</span><span>Взнос</span><span>Дорога и проживание</span><span>Прочее</span><span>Итого</span></div>{data.tournaments.map(x => <div key={x.id}><span><strong>{x.name}</strong><small>{x.status}</small></span><span>{money(x.entryFee)}</span><span>{money(x.travelCost + x.accommodationCost)}</span><span>{money(x.mealCost + x.equipmentCost + x.otherCost)}</span><strong>{money(tournamentExpense(x))}</strong></div>)}</section></> }
function tournamentExpense(x: Workspace['tournaments'][number]) { return x.entryFee + x.travelCost + x.accommodationCost + x.mealCost + x.equipmentCost + x.otherCost }
function money(value: number) { return new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 }).format(value) }
