import { useState, type FormEvent, type ReactNode } from 'react'
import { CityInput } from '../CityInput'
import { post, put } from '../api'
import { EmptyState, ErrorState, PageHeader, PageLoader, StatCard } from '../components'
import { useApiData } from '../hooks'

type Membership = { schoolId: number; name: string; role: string }
type Overview = { id: number; name: string; slug: string; city?: string; contactEmail?: string; phone?: string; logoUrl?: string; isActive: boolean; teams: number; coaches: number; players: number }
type Team = { id: number; name: string; ageGroup?: string; season?: string; isActive: boolean; players: number; coaches: { coachId: number; displayName: string; isHeadCoach: boolean }[] }
type Coach = { userId: string; email: string; isActive: boolean; coachId?: number; displayName?: string }
type Player = { playerId: number; firstName: string; lastName: string; dateOfBirth: string; city: string; preferredPosition: string; teamId: number; team: string; shirtNumber?: number }
type Invite = { id: number; email: string; inviteUrl?: string; expiresAt?: string }

function SchoolBoundary({ children }: { children: (schoolId: number) => ReactNode }) {
  const state = useApiData<Membership[]>('/api/school/memberships')
  if (state.loading) return <PageLoader />
  if (state.error) return <ErrorState message={state.error} retry={state.reload} />
  const schoolId = state.data?.[0]?.schoolId
  if (!schoolId) return <EmptyState title="Нет доступной школы">Обратитесь к администратору платформы.</EmptyState>
  return children(schoolId)
}

export function SchoolDashboardPage() { return <SchoolBoundary>{schoolId => <SchoolOverview schoolId={schoolId} />}</SchoolBoundary> }
function SchoolOverview({ schoolId }: { schoolId: number }) {
  const state = useApiData<Overview>(`/api/school/${schoolId}/overview`)
  if (state.loading) return <PageLoader />
  if (state.error || !state.data) return <ErrorState message={state.error} retry={state.reload} />
  return <><PageHeader eyebrow="Управление школой" title={state.data.name} /><section className="stat-grid"><StatCard label="Команд" value={state.data.teams} tone="accent" /><StatCard label="Тренеров" value={state.data.coaches} /><StatCard label="Игроков" value={state.data.players} /></section><section className="card school-welcome"><div><span className="eyebrow">Единый контур</span><h2>Люди собраны по реальным командам</h2><p>Назначьте тренеров и добавьте составы — после этого каждый тренер увидит только своих игроков.</p></div><span className="school-monogram">{state.data.name[0]}</span></section></>
}

export function SchoolTeamsPage() { return <SchoolBoundary>{schoolId => <Teams schoolId={schoolId} />}</SchoolBoundary> }
function Teams({ schoolId }: { schoolId: number }) {
  const state = useApiData<Team[]>(`/api/school/${schoolId}/teams`); const coaches = useApiData<Coach[]>(`/api/school/${schoolId}/coaches`); const [message, setMessage] = useState('')
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const f = new FormData(form); try { await post(`/api/school/${schoolId}/teams`, { name: f.get('name'), ageGroup: f.get('ageGroup'), season: f.get('season'), isActive: true }); form.reset(); setMessage('Команда создана.'); await state.reload() } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось создать команду.') } }
  const assign = async (event: FormEvent<HTMLFormElement>, teamId: number) => { event.preventDefault(); const f = new FormData(event.currentTarget); try { await post(`/api/school/${schoolId}/teams/${teamId}/coaches`, { coachId: Number(f.get('coachId')), isHeadCoach: f.get('isHeadCoach') === 'on' }); setMessage('Тренер назначен.'); await state.reload() } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось назначить тренера.') } }
  return <><PageHeader eyebrow="Школа" title="Команды" /><section className="card form-card"><h2>Новая команда</h2><form className="profile-form" onSubmit={create}><label>Название<input name="name" placeholder="U14 — основная" required /></label><label>Возраст<input name="ageGroup" placeholder="2012–2013" /></label><label>Сезон<input name="season" placeholder="2026/27" /></label><div className="form-actions"><button className="button">Создать</button></div></form></section>{message && <p className="success-message">{message}</p>}{state.loading ? <PageLoader /> : state.error || !state.data ? <ErrorState message={state.error} retry={state.reload} /> : <section className="school-card-grid">{state.data.map(team => <article className={`card team-card ${team.isActive ? '' : 'inactive'}`} key={team.id}><div className="card-heading"><div><h2>{team.name}</h2><small>{[team.ageGroup, team.season].filter(Boolean).join(' · ') || 'Без возрастной группы'}</small></div><span className="count-chip">{team.players} игроков</span></div><div className="team-coaches">{team.coaches.length ? team.coaches.map(x => <span key={x.coachId}>{x.isHeadCoach ? '★ ' : ''}{x.displayName}</span>) : <small>Тренер ещё не назначен</small>}</div>{coaches.data?.some(x => x.coachId) && <form className="inline-assign" onSubmit={e => void assign(e, team.id)}><select name="coachId" required><option value="">Выберите тренера</option>{coaches.data.filter(x => x.coachId).map(x => <option key={x.userId} value={x.coachId}>{x.displayName}</option>)}</select><label className="checkbox"><input name="isHeadCoach" type="checkbox" />Главный</label><button className="button ghost">Назначить</button></form>}</article>)}</section>}</>
}

export function SchoolCoachesPage() { return <SchoolBoundary>{schoolId => <Coaches schoolId={schoolId} />}</SchoolBoundary> }
function Coaches({ schoolId }: { schoolId: number }) {
  const state = useApiData<Coach[]>(`/api/school/${schoolId}/coaches`); const [invite, setInvite] = useState<Invite | null>(null); const [message, setMessage] = useState('')
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const f = new FormData(form); try { const result = await post<Invite>(`/api/school/${schoolId}/coaches`, { email: f.get('email'), displayName: f.get('displayName') }); setInvite(result); setMessage(result.inviteUrl ? 'Тренер добавлен. Передайте ему ссылку в течение 24 часов.' : 'Тренер добавлен с существующим аккаунтом.'); form.reset(); await state.reload() } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось добавить тренера.') } }
  return <><PageHeader eyebrow="Школа" title="Тренеры" /><section className="card form-card"><h2>Пригласить тренера</h2><form className="profile-form" onSubmit={submit}><label>Имя и фамилия<input name="displayName" required /></label><label>Email<input name="email" type="email" required /></label><div className="form-actions"><button className="button">Добавить тренера</button></div>{message && <span className="success-message full">{message}</span>}{invite?.inviteUrl && <div className="invite-result full"><label>Одноразовая ссылка<input value={invite.inviteUrl} readOnly onFocus={e => e.currentTarget.select()} /></label><button type="button" className="button ghost" onClick={() => void navigator.clipboard.writeText(invite.inviteUrl!)}>Копировать</button></div>}</form></section>{state.loading ? <PageLoader /> : state.error || !state.data ? <ErrorState message={state.error} retry={state.reload} /> : <section className="card simple-list">{state.data.length ? state.data.map(x => <article key={x.userId}><strong>{x.displayName}</strong><span>{x.email}</span><small>{x.isActive ? 'Активен' : 'Отключён'}</small></article>) : <EmptyState title="Тренеров пока нет" />}</section>}</>
}

export function SchoolPlayersPage() { return <SchoolBoundary>{schoolId => <Players schoolId={schoolId} />}</SchoolBoundary> }
function Players({ schoolId }: { schoolId: number }) {
  const state = useApiData<Player[]>(`/api/school/${schoolId}/players`); const teams = useApiData<Team[]>(`/api/school/${schoolId}/teams`); const [message, setMessage] = useState('')
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const f = new FormData(form); try { await post(`/api/school/${schoolId}/players`, { firstName: f.get('firstName'), lastName: f.get('lastName'), dateOfBirth: f.get('dateOfBirth'), city: f.get('city'), preferredPosition: f.get('preferredPosition'), dominantFoot: f.get('dominantFoot'), experienceLevel: f.get('experienceLevel'), teamId: Number(f.get('teamId')), shirtNumber: f.get('shirtNumber') ? Number(f.get('shirtNumber')) : null }); form.reset(); setMessage('Игрок добавлен в команду.'); await state.reload() } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось добавить игрока.') } }
  return <><PageHeader eyebrow="Школа" title="Игроки" /><section className="card form-card"><h2>Новый игрок</h2><p className="legal-note">Профиль без самостоятельного входа. Доступ родителя подключается отдельным приглашением.</p><form className="profile-form" onSubmit={submit}><label>Имя<input name="firstName" required /></label><label>Фамилия<input name="lastName" required /></label><label>Дата рождения<input name="dateOfBirth" type="date" required /></label><label>Город<CityInput required /></label><label>Позиция<select name="preferredPosition"><option>Нападающий</option><option>Полузащитник</option><option>Защитник</option><option>Вратарь</option></select></label><label>Ведущая нога<select name="dominantFoot"><option>Правая</option><option>Левая</option><option>Обе</option></select></label><label>Уровень<select name="experienceLevel"><option>Начинающий</option><option>Любитель</option><option>Продвинутый</option></select></label><label>Команда<select name="teamId" required><option value="">Выберите команду</option>{teams.data?.filter(x => x.isActive).map(x => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Номер<input name="shirtNumber" type="number" min="1" max="99" /></label><div className="form-actions"><button className="button" disabled={!teams.data?.some(x => x.isActive)}>Добавить</button></div></form>{message && <p className="success-message">{message}</p>}</section>{state.loading ? <PageLoader /> : state.error || !state.data ? <ErrorState message={state.error} retry={state.reload} /> : <section className="card data-table school-players"><div className="table-head"><span>Игрок</span><span>Команда</span><span>Позиция</span><span>Город</span></div>{state.data.map(x => <div key={`${x.teamId}-${x.playerId}`}><span><strong>{x.firstName} {x.lastName}</strong><small>{x.dateOfBirth}</small></span><span>{x.team}{x.shirtNumber && <small>№ {x.shirtNumber}</small>}</span><span>{x.preferredPosition}</span><span>{x.city}</span></div>)}</section>}</>
}

export function SchoolSettingsPage() { return <SchoolBoundary>{schoolId => <Settings schoolId={schoolId} />}</SchoolBoundary> }
function Settings({ schoolId }: { schoolId: number }) {
  const state = useApiData<Overview>(`/api/school/${schoolId}/overview`); const [message, setMessage] = useState('')
  if (state.loading) return <PageLoader />; if (state.error || !state.data) return <ErrorState message={state.error} retry={state.reload} />
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const f = new FormData(event.currentTarget); try { await put(`/api/school/${schoolId}/settings`, { name: f.get('name'), city: f.get('city'), contactEmail: f.get('contactEmail'), phone: f.get('phone'), logoUrl: f.get('logoUrl') }); setMessage('Настройки сохранены.'); await state.reload() } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось сохранить настройки.') } }
  return <><PageHeader eyebrow="Школа" title="Настройки" /><section className="card form-card"><form className="profile-form" onSubmit={save}><label>Название<input name="name" defaultValue={state.data.name} required /></label><label>Город<input name="city" defaultValue={state.data.city} /></label><label>Email<input name="contactEmail" type="email" defaultValue={state.data.contactEmail} /></label><label>Телефон<input name="phone" defaultValue={state.data.phone} /></label><label className="full">Ссылка на логотип<input name="logoUrl" type="url" defaultValue={state.data.logoUrl} /></label><div className="form-actions"><button className="button">Сохранить</button>{message && <span className="success-message">{message}</span>}</div></form></section></>
}

type AdminSchool = Overview & { ownerEmail?: string; createdAt: string }
type AdminSchoolCreate = { id: number; name: string; ownerEmail: string; inviteUrl?: string; expiresAt?: string }
export function AdminSchoolsPage() {
  const state = useApiData<AdminSchool[]>('/api/admin/schools'); const [result, setResult] = useState<AdminSchoolCreate | null>(null); const [message, setMessage] = useState('')
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const f = new FormData(form); try { const next = await post<AdminSchoolCreate>('/api/admin/schools', { name: f.get('name'), ownerEmail: f.get('ownerEmail'), city: f.get('city'), contactEmail: f.get('contactEmail'), phone: f.get('phone') }); setResult(next); setMessage('Школа создана.'); form.reset(); await state.reload() } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось создать школу.') } }
  const toggle = async (school: AdminSchool) => { try { await put(`/api/admin/schools/${school.id}/status`, { isActive: !school.isActive }); await state.reload() } catch (e) { setMessage(e instanceof Error ? e.message : 'Не удалось изменить статус.') } }
  return <><PageHeader eyebrow="Платформа" title="Школы" /><section className="card form-card"><h2>Подключить школу</h2><form className="profile-form" onSubmit={create}><label>Название<input name="name" required /></label><label>Email владельца<input name="ownerEmail" type="email" required /></label><label>Город<input name="city" /></label><label>Контактный email<input name="contactEmail" type="email" /></label><label>Телефон<input name="phone" /></label><div className="form-actions"><button className="button">Создать школу</button></div>{message && <span className="success-message full">{message}</span>}{result?.inviteUrl && <div className="invite-result full"><label>Приглашение владельца<input value={result.inviteUrl} readOnly onFocus={e => e.currentTarget.select()} /></label><button type="button" className="button ghost" onClick={() => void navigator.clipboard.writeText(result.inviteUrl!)}>Копировать</button></div>}</form></section>{state.loading ? <PageLoader /> : state.error || !state.data ? <ErrorState message={state.error} retry={state.reload} /> : <section className="school-card-grid">{state.data.map(x => <article className={`card team-card ${x.isActive ? '' : 'inactive'}`} key={x.id}><div className="card-heading"><div><h2>{x.name}</h2><small>{x.city || 'Город не указан'} · {x.ownerEmail}</small></div><span className="count-chip">{x.isActive ? 'Активна' : 'Заблокирована'}</span></div><div className="school-metrics"><span><b>{x.teams}</b> команд</span><span><b>{x.coaches}</b> тренеров</span><span><b>{x.players}</b> игроков</span></div><button className={`button ghost ${x.isActive ? 'danger' : ''}`} onClick={() => void toggle(x)}>{x.isActive ? 'Заблокировать' : 'Разблокировать'}</button></article>)}</section>}</>
}
