// <auto-generated />
using Kasanie.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kasanie.Api.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20261005170000_AddTeamTrainingTemplates")]
partial class AddTeamTrainingTemplates
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
#pragma warning restore 612, 618
    }
}
